DROP TABLE Employee;
DROP TABLE order_breakout;
DROP TABLE Food_to_inventory;
DROP TABLE Food_to_inventory_Inventory;
DROP TABLE order_breakout_Menu_Items;
DROP TABLE Orders;
DROP TABLE Inventory;
DROP TABLE Customer;
DROP TABLE Menu_Items;